singleQuote: true
tabWidth: 4
printWidth: 120
trailingComma: "all"
overrides:
  - files: ["*.js", "*.jsx", "*.ts", "*.tsx"]
    options:
      tabWidth: 2
  - files: ["*.yml", "*.yaml"]
    options:
      singleQuote: false
      tabWidth: 2
