tabWidth: 4
printWidth: 100
singleQuote: true
trailingComma: "all"
overrides:
  - files: ["*.js", "*.jsx", "*.ts", "*.tsx"]
    options:
      tabWidth: 2
  - files: ["*.json"]
    options:
      tabWidth: 2
      bracketSpacing: true
  - files: ["*.yml", "*.yaml"]
    options:
      singleQuote: false
      tabWidth: 2
  - files: ["Makefile"]
    options:
      singleQuote: false
      tabWidth: 2
      useTabs: true
