singleQuote: true
tabWidth: 4
max-line-length: 120
printWidth: 120
overrides:
  - files: ["*.js*", "*.ts*", "*.json"]
    options:
      tabWidth: 2
  - files: ["*.yml", "*.yaml"]
    options:
      singleQuote: false
      tabWidth: 2
