sudo: required
language: node_js
node_js: 10
services:
- docker
cache: yarn
jobs:
  include:
#   - stage: test
#     name: docker build and push
#     install: true
#     script: make dockerhub_push
  - stage: test
    name: unit tests
    install: make install_ci
    script: make test_unit_codecov
  - stage: test
    install: make install
    name: lint
    script: make lint
