name: Pull Request
on: pull_request

jobs:
  test_image_build:
    name: Test build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build .
